export const TAGS = '/static/json/tag.json'
export const SELLER = '/static/json/seller.json'
export const ORDER = '/static/json/order.json'
export const GOODS = '/static/json/goods.json'
export const CATEGORIES = '/static/json/categories.json'
